from django.contrib import admin
from .models import *


admin.site.register(Home)
admin.site.register(HomeContact)
admin.site.register(Info)
admin.site.register(InfoCard)
admin.site.register(Exam)
admin.site.register(ExamCard)
admin.site.register(ExamTheme)
admin.site.register(Video)
admin.site.register(VideoItem)
admin.site.register(ClientContact)
admin.site.register(MotionContact)
admin.site.register(About)
admin.site.register(Team)
admin.site.register(Person)
admin.site.register(Study)
admin.site.register(CountryPage)
admin.site.register(CountryName)
admin.site.register(ProgramType)
admin.site.register(Speciality)
admin.site.register(Language)
admin.site.register(Country)
admin.site.register(CountryDescriptionCost)
admin.site.register(CountryPhoto)
admin.site.register(CountryInfo)
admin.site.register(University)
admin.site.register(UniversityInfo)
admin.site.register(UniversityEvent)
admin.site.register(UniversityEventInfo)
admin.site.register(UniversityCost)
admin.site.register(UniversityPhoto)
admin.site.register(Share)
