# Generated by Django 5.2.2 on 2025-06-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('info', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='title_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='title_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='title_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='title_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='title_ky',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='title_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='examcard',
            name='title_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='examcard',
            name='title_ky',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='examcard',
            name='title_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='examtheme',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='examtheme',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='examtheme',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='examtheme',
            name='theme_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='examtheme',
            name='theme_ky',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='examtheme',
            name='theme_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='label_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='label_ky',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='label_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='title_ky',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='title_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='title_ky',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='title_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='infocard',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='infocard',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='infocard',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='infocard',
            name='title_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='infocard',
            name='title_ky',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='infocard',
            name='title_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='motioncontact',
            name='title_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='motioncontact',
            name='title_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='motioncontact',
            name='title_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title_ky',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title_ru',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
