# Generated by Django 5.2.2 on 2025-06-05 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0002_share_clientcontact_title_en_clientcontact_title_ky_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('info_en', models.TextField(null=True)),
                ('info_ru', models.TextField(null=True)),
                ('info_ky', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('title_en', models.CharField(max_length=64, null=True)),
                ('title_ru', models.CharField(max_length=64, null=True)),
                ('title_ky', models.CharField(max_length=64, null=True)),
                ('information', models.TextField()),
                ('information_en', models.TextField(null=True)),
                ('information_ru', models.TextField(null=True)),
                ('information_ky', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityEventInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('title_en', models.CharField(max_length=64, null=True)),
                ('title_ru', models.CharField(max_length=64, null=True)),
                ('title_ky', models.CharField(max_length=64, null=True)),
                ('information', models.TextField()),
                ('information_en', models.TextField(null=True)),
                ('information_ru', models.TextField(null=True)),
                ('information_ky', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('title_en', models.CharField(max_length=64, null=True)),
                ('title_ru', models.CharField(max_length=64, null=True)),
                ('title_ky', models.CharField(max_length=64, null=True)),
                ('information', models.TextField()),
                ('information_en', models.TextField(null=True)),
                ('information_ru', models.TextField(null=True)),
                ('information_ky', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='label_en',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='label_ky',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='label_ru',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ky',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='countrydescriptioncost',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='countrydescriptioncost',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='countrydescriptioncost',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='countryinfo',
            name='information_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='countryinfo',
            name='information_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='countryinfo',
            name='information_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='countryinfo',
            name='title_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='countryinfo',
            name='title_ky',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='countryinfo',
            name='title_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='countryname',
            name='country_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='countryname',
            name='country_name_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='countryname',
            name='country_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='countrypage',
            name='title_en',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='countrypage',
            name='title_ky',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='countrypage',
            name='title_ru',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='language_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='language_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='language_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='info_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='info_ky',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='info_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='programtype',
            name='program_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='programtype',
            name='program_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='programtype',
            name='program_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='info_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='info_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='info_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='title_en',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='title_ky',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='title_ru',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='speciality_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='speciality_name_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='speciality_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='bonus_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='bonus_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='bonus_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='title_en',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='title_ky',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='title_ru',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='title_en',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='title_ky',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='title_ru',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('title_en', models.CharField(max_length=64, null=True)),
                ('title_ru', models.CharField(max_length=64, null=True)),
                ('title_ky', models.CharField(max_length=64, null=True)),
                ('foundation_date', models.DateField()),
                ('language', models.ManyToManyField(to='motion.language')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motion.countryname')),
                ('program_type', models.ManyToManyField(to='motion.programtype')),
                ('speciality', models.ManyToManyField(to='motion.speciality')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_photos', models.ImageField(upload_to='university_photos/')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motion.university')),
            ],
        ),
    ]
