# Generated by Django 5.2.2 on 2025-06-06 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0003_universitycost_universityevent_universityeventinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtheme',
            name='exam_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motion.examcard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universitycost',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motion.university'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universityevent',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motion.university'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universityeventinfo',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motion.universityevent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universityinfo',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motion.university'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='countryinfo',
            name='country_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motion.country'),
        ),
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motion.country'),
        ),
    ]
