# Generated by Django 5.2.2 on 2025-06-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0004_examtheme_exam_card_universitycost_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitycost',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universitycost',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='universitycost',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='universitycost',
            name='text_ru',
            field=models.TextField(null=True),
        ),
    ]
