# Generated by Django 5.2.2 on 2025-06-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0006_alter_countrypage_title_alter_countrypage_title_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='flag',
            new_name='flag1',
        ),
        migrations.AddField(
            model_name='country',
            name='flag2',
            field=models.ImageField(default=1, upload_to='country_flags/'),
            preserve_default=False,
        ),
    ]
