# Generated by Django 5.2.2 on 2025-06-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0009_university_photo_alter_country_country_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoitem',
            name='videos',
            field=models.URLField(),
        ),
    ]
