# Generated by Django 5.2.2 on 2025-06-17 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0010_alter_videoitem_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_universities', to='motion.country'),
        ),
    ]
